num_keypoints: 10
batch_size: 20
dataset: 'CelebA'
tps_control_pts: 5
lr: 0.0001
epochs: 20
heatmap_std: 0.1
tps_variance: 0.05
max_rot: 0.1
data_rescale_height: 128
data_rescale_width: 128
split: 'random'
trainratio: 0.9
testratio: 0.1
#pretrained: '/home/chen/Projects/IMM_pytorch/Celeba_experiment4/checkpoint_model_CelebA.pt'
run_id: 'Celeba_originaldata_experiment2'

